name: Debug cache
on:
  workflow_dispatch:
    inputs:
      page_name:
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # We need full git history to use git merge-base
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - uses: actions/cache/restore@v4
      with:
        path: cache/*
        key: tfwiki-file-cache-invalid
        restore-keys: tfwiki-file-cache- # Restores the most recent cache
    - run: python -u debug_cache.py ${{ inputs.page_name }}

