name: TFWiki Stats
on:
  schedule:
    - cron: '0 1 * * *' # Run the script daily, the script itself controls which reports are run
  workflow_dispatch:
    inputs:
      reports:
        type: string
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # We need full git history to use git merge-base
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - uses: actions/cache/restore@v4
      with:
        path: cache/*
        key: tfwiki-file-cache-invalid
        restore-keys: tfwiki-file-cache- # Restores the most recent cache
    - run: python -u master.py ${{ inputs.reports }}
      timeout-minutes: 360
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
    - uses: actions/cache/save@v4
      if: always()
      with:
        path: cache/*
        key: tfwiki-file-cache-${{ github.run_id }} # Caches are immutable; we must create a new one each run.
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Failed uploads
        path: reports/wiki_*.txt
        if-no-files-found: ignore
